language: java

sudo: false

jdk:
  - oraclejdk8

env:
  global:
    - secure: EABgExLINeb4BCw43u3MwED9G2ZW6mDscNvHngEcv0ko27dXnjKtkhY7TUnaQUM1euXqkHfFXG3HqCXiEYD4OXUmVKbh0qlnd1TJkckKJtbHfzBTppBfSZASSkBkltIKxplN2Nf+k+h4eOAh+/Z7DVzLkg/Ms9bCTjgTHPvT0ueA7cWfJYnVUMNQkvGcDm8RB2gYAujihrWbBd1UVXTZPv65pMOe1iwWcwMjY91kDNM81qcNE64V3Jd3oqbu62nTbYRB1AXQeOlFoS8Cz/MiusNy+VJP93OAqNrT5JwTJrblUMkS1zlf92oFtKD3OKjrN0H4Vf+pbOBLn54usK2KcElA1LIoU1EntnMzW4Jpn3+a8Mb/O/TmdVFV6NNxc3n/8iGg41L44mGnycls2TAGj8Z9fFa5aHLPF3nivx74Co2kjwva+ywEa++RitNhv7D10p1rEF3FaFCNZb4EDjxnI8KfQ3j6sWMcrOK9mnAvsUT41HHbCUEXXTxhBSpJm7Rvfl2bPVaGARTo/nhnkeASSrIm2HLCObCAqLJrYaHp86zjxfTIQX1WDZtWBiyJHJXwrD2yEcDPF4NUEroAojJCRR4knBFEovIbOV5J94FbwzZhhVWrZGpc81jjbwSzWUBZW/XugBDoHl8XYYj1nwTKbBeyErrZqNVPoaOljdNXabw=
    - secure: bMRVKs3ZeCMVBaXz96wzQey8eCmKHRqKIS686WLK2U6gK5A68EnzFb4yGso1dR13cOW2NPnlw7KsxzNPqBYFvCC66QCOkS78C9GWc4CBhBkJOGWlLSxdJZ/eWzy4X0MFKcq93fs4jlsdGSjCd9lDRpNeNipEqRiTq4pAiY0JPisDdtCQ1jUwF4PvafmFXDKrNCB96KXkB3tmUNreAXGzsD0QH5y+ndQ2BesHfMW6YYqJdQDovzETvIzR9uX73fYBypT3chwdCro5Lzwmba0aa7rkG8/awH+QeJZMNG3WGLvfP7l+Y/qzFB0+38Rs/ifXuQWeVKmAcobap4nJWlA28K8E2nWN+9DdOkdzG2CUuHbesJC9BxlqBwLaZ87VbUyxall7E4NXtZ81W7r2QbDOO5TumyiCsOZogiUF3KmBl+0nCyReYXlbNxtsqgEmeEqqDItBtv1oufpHocZ0WbPfiF7kXAwLK31kOFL6a8ZXU8HwFIkFCOosGNFc+P7X528lpUxl/aoZPS3Nclvvc2m7ZY6aGZkbBmwBSnUA323cGmugWPFubCBOSCm3D9rI1VArLmOINdSdBUQDD93AFSdUR17y08RMjKPf2+72L9oRYNMaRJQoesAcLLlpIInoyNTo7eg59EthUKrPmMqZAPG71WQ1eZzr/w1+zCf4kloUCC4=

addons:
  apt:
    packages:
      - python-yaml

before_script:
  - python etc/travis-sonatype.py

script: python etc/travis-build.py --settings ~/.m2/sonatype.xml
